info:
    app:
        profile: developer
        name: "@name@"
        description: "@description@"
        version: "@project.version@"

server:
    context-path: /

heimdall:
    contextPath: /heimdall/v1
    hostname: hostname
    excludeRabbit: true
    retryable: false
    splunk:
        enabled: false
        #destination:
    rewrite:
        enable: false
        prefix: heimdall
    datasource:
        initializationFailTimeout: -1
        dataBaseType: SQLServer
        socketTimeout: 10000
        loginTimeout: 10000
        minimumIdle: 0
        maximumPoolSize: 50
        validationTimeout: 10000
        idleTimeout: 10000
        connectionTimeout: 10000
        dataSourceClassName: com.microsoft.sqlserver.jdbc.SQLServerDataSource
        connectionTestQuery: SELECT 1
        autoCommit: false
        initializationFailFast: false
        appName: HEIMDALL
        databaseName: HEIMDALL
        portNumber: 1433
        serverName: 10.60.30.91
        username: UserPier
        password: UserPier
        runLiquibase: true
        sendStringParametersAsUnicode: false
    mongo:
        enabled: false
        serverName: 192.168.10.203
        #url:
        port: 27017
        dataBase: logging
        collection: logs
        username: admin
        password: admin
    trace:
        printAllTrace: true
        sanitizes:
            - access_token
            - client_id
    redis:
        host: 192.168.10.200
        port: 6379
        maxTotal: 128
        maxIdle: 128
        minIdle: 16
        testOnBorrow: true
        testOnReturn: true
        testWhileIdle: true
        minEvictableIdleTimeSeconds: 60
        timeBetweenEvictionRunsSeconds: 30
        numTestsPerEvictionRun: 3
        blockWhenExhausted: true
        connectionPoolSize: 10
    security:
        enabled: true
        ldap:
            enabled: false
            #url: ldap://your.host:port
            #searchBase: DC=name,DC=name
            #userDn: your@mail.user
            #password: password
            #userSearchFilter: sAMAccountName={0}    
     middlewares:
        allowInactive: 0
        deleteDeprecated: false

spring:
    pid:
        fail-on-write-error: false
        file: heimdall.pid
    jpa:
        database-platform: org.hibernate.dialect.SQLServer2012Dialect
        database: SQL_SERVER
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    jackson:
        serialization:
            INDENT_OUTPUT: true
            WRITE-DATES-AS-TIMESTAMPS: false
    rabbitmq:
        host: 192.168.10.200
        port: 5672
        virtual-host: desenvolvimento
        requested-heartbeat: 10
    cache:
        type: redis

springfox:
    documentation:
        swagger:
            v2:
                path: /docs
                
endpoints:    
    routes:
        enabled: true
        sensitive: false
    actuator:
        enabled: true

management:
    context-path: /manager
    security:
        enabled: false
    health:
        mongo:
            enabled: false
        redis:
            enabled: false
        rabbit:
            enabled: false
        hystrix:
            enabled: false
        refresh:
            enabled: false

zuul:
    filter:
        root: /tmp/interceptores
        
security:
    basic:
        enabled: false
