info:
    app:
        profile: developer
        name: asgard
        description: Asgard Project
        version: 1.5.0-SNAPSHOT
        
server:
    port: 8080
    context-path: /
    tomcat:
        max-threads: 300
    
heimdall:
    hostname: nome-da-maquina
    excludeRabbit: true
    retryable: false
    splunk:
        enabled: false
        destination: 10.1.1.241:15893
    rewrite: 
        enable: false
        prefix: heimdall
    datasource:
        initializationFailTimeout: -1
        dataBaseType: SQLServer
        socketTimeout: 10000
        loginTimeout: 10000
        minimumIdle: 0
        maximumPoolSize: 50
        validationTimeout: 10000
        idleTimeout: 10000
        connectionTimeout: 10000
        dataSourceClassName: com.microsoft.sqlserver.jdbc.SQLServerDataSource
        connectionTestQuery: SELECT 1
        autoCommit: false
        initializationFailFast: false        
        appName: HEIMDALL
        databaseName: HEIMDALL_HMLG_EXT
        portNumber: 1433
        serverName: 10.19.20.21
        username: UserPier
        password: UserPier        
        runLiquibase: true
        sendStringParametersAsUnicode: false
    mongo:
        enabled: false
        serverName: 192.168.10.203
        #url: 
        port: 27017
        dataBase: logging
        collection: logs
        username: admin
        password: admin
    trace:
        printAllTrace: true
        sanitizes:
            - access_token
            - client_id
    redis:
        #host: 192.168.10.200
        host: 10.60.30.49
        port: 6379
        maxTotal: 128
        maxIdle: 128
        minIdle: 16
        testOnBorrow: true
        testOnReturn: true
        testWhileIdle: true
        minEvictableIdleTimeSeconds: 60
        timeBetweenEvictionRunsSeconds: 30
        numTestsPerEvictionRun: 3
        blockWhenExhausted: true
        connectionPoolSize: 10

spring:
    pid:
        fail-on-write-error: false
        file: heimdall.pid
    jpa:
        database-platform: org.hibernate.dialect.SQLServer2012Dialect
        database: SQL_SERVER    
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    jackson:
        serialization:
            INDENT_OUTPUT: true
            WRITE-DATES-AS-TIMESTAMPS: false
    rabbitmq:
        #host: 192.168.10.200
        host: 10.60.30.49
        port: 5672
        virtual-host: desenvolvimento
        requested-heartbeat: 10
    cache:
        type: redis
        
sentry:
    dsn: http://3a1e8e8a5a6d443bb4697920a49f3f07:73bfa411de75441da31c77cd6d36db3c@10.50.10.30:9000/7
    environment: hmlg
    release: 1.5.0-SNAPSHOT
    tags: heimdall-gateway
    profiles:
        active: hmlg
                
endpoints:    
    routes:
        enabled: true
        sensitive: false
    actuator: 
        enabled: true

zuul:
    #servletPath: /
    include-debug-header: false
    debug: 
        parameter: debug
        request: true
    filter: 
        interval: 5
        root: /tmp/interceptores
    host: 
        socket-timeout-millis: 40000
        connect-timeout-millis: 40000

management:
    context-path: /manager
    security:
        enabled: false
    health: 
        mongo: 
            enabled: false
        redis: 
            enabled: false
        rabbit: 
            enabled: false    
        hystrix: 
            enabled: false    
        refresh: 
            enabled: false          